sudo: required
services:
  - docker

before_install:
  - docker build -t linneakawe/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run linneakawe/react-test npm test -- --coverage

after_success:
  - docker build -t linneakawe/multi-client ./client
  - docker build -t linneakawe/multi-nginx ./nginx
  - docker build -t linneakawe/multi-server ./server
  - docker build -t linneakawe/multi-worker ./worker
# Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# Take those images and push them to docker hub
  - docker push linneakawe/multi-client
  - docker push linneakawe/multi-nginx
  - docker push linneakawe/multi-server
  - docker push linneakawe/multi-worker

language: generic